const team_logos: {[key: string]: any} = {
    ATL: require('../assets/logos/ATL.png'),
    BOS: require('../assets/logos/BOS.png'),
    BKN: require('../assets/logos/BKN.png'),
    CHA: require('../assets/logos/CHA.png'),
    CHI: require('../assets/logos/CHI.png'),
    CLE: require('../assets/logos/CLE.png'),
    DAL: require('../assets/logos/DAL.png'),
    DEN: require('../assets/logos/DEN.png'),
    DET: require('../assets/logos/DET.png'),
    GSW: require('../assets/logos/GSW.png'),
    HOU: require('../assets/logos/HOU.png'),
    IND: require('../assets/logos/IND.png'),
    LAC: require('../assets/logos/LAC.png'),
    LAL: require('../assets/logos/LAL.png'),
    MEM: require('../assets/logos/MEM.png'),
    MIA: require('../assets/logos/MIA.png'),
    MIL: require('../assets/logos/MIL.png'),
    MIN: require('../assets/logos/MIN.png'),
    NOP: require('../assets/logos/NOP.png'),
    NYK: require('../assets/logos/NYK.png'),
    OKC: require('../assets/logos/OKC.png'),
    ORL: require('../assets/logos/ORL.png'),
    PHI: require('../assets/logos/PHI.png'),
    PHX: require('../assets/logos/PHX.png'),
    POR: require('../assets/logos/POR.png'),
    SAC: require('../assets/logos/SAC.png'),
    SAS: require('../assets/logos/SAS.png'),
    TOR: require('../assets/logos/TOR.png'),
    UTA: require('../assets/logos/UTH.png'),
    WAS: require('../assets/logos/WAS.png'),
  };
  
  export default team_logos;
  